// LocalAssistant Production Vocabulary
// Merged and cleaned from existing vocabulary and expansion pack
// All duplicates removed, quality words only
// Total: 6654 words across 17 categories

const vocabulary = {
    // verbs: 1575 words
    verbs: [
        'abandon', 'abbreviate', 'abdicate', 'abduct', 'ability', 'abolish', 'abound', 'about', 'above', 'abroad', 'abrupt', 'abstain', 'abstract', 'abuse', 'accelerate', 
        'accept', 'access', 'accommodate', 'accompany', 'accomplish', 'accord', 'accrue', 'accumulate', 'accuse', 'accustom', 'achieve', 'acknowledge', 'acquaint', 'acquire', 'acquit', 
        'act', 'activate', 'actuate', 'adapt', 'add', 'addict', 'address', 'adhere', 'adjoin', 'adjourn', 'adjudicate', 'adjust', 'administer', 'admire', 'admit', 
        'admix', 'admonish', 'adopt', 'adore', 'adorn', 'adulterate', 'advance', 'advertise', 'advise', 'advocate', 'aerate', 'affect', 'afford', 'affront', 'afraid', 
        'age', 'agitate', 'agree', 'aid', 'ail', 'aim', 'air', 'alarm', 'alienate', 'align', 'allege', 'alleviate', 'allocate', 'allot', 'allow', 
        'allude', 'allure', 'ally', 'alter', 'alternate', 'amalgamate', 'amass', 'amaze', 'amend', 'amount', 'amplify', 'amuse', 'analyze', 'anchor', 'animate', 
        'announce', 'annoy', 'annul', 'anoint', 'answer', 'antagonize', 'anticipate', 'antics', 'appeal', 'appear', 'appease', 'append', 'applaud', 'apply', 'appoint', 
        'appreciate', 'apprehend', 'apprentice', 'apprise', 'approach', 'approve', 'approximate', 'arbitrate', 'arrange', 'arrest', 'arrive', 'arrogate', 'articulate', 'ascend', 'ascertain', 
        'ascribe', 'ash', 'ask', 'aspire', 'assault', 'assay', 'assemble', 'assent', 'assert', 'assess', 'assign', 'assimilate', 'assist', 'associate', 'assort', 
        'assuage', 'assume', 'assure', 'astonish', 'astound', 'astray', 'attach', 'attack', 'attain', 'attempt', 'attend', 'attest', 'attire', 'attract', 'attune', 
        'auction', 'audit', 'augment', 'augur', 'auspice', 'authenticate', 'authorize', 'auto', 'avail', 'avalanche', 'avarice', 'avenge', 'avenue', 'aver', 'average', 
        'avert', 'avid', 'avoid', 'avow', 'await', 'awake', 'awaken', 'award', 'aware', 'awash', 'away', 'awe', 'awesome', 'awful', 'awhile', 
        'awkward', 'awl', 'awning', 'awoke', 'awry', 'axe', 'axiom', 'axis', 'axle', 'aye', 'azure', 'babble', 'baby', 'back', 'backbite', 
        'backbone', 'backdoor', 'backdrop', 'backer', 'backfire', 'backhand', 'backing', 'backlash', 'backlog', 'backpack', 'backslide', 'backstab', 'backstage', 'backstroke', 'backtrack', 
        'backup', 'backward', 'backwards', 'backwater', 'bacon', 'bacteria', 'bacterium', 'bad', 'badge', 'badger', 'baffle', 'bag', 'baggage', 'baggy', 'bail', 
        'bait', 'bake', 'bakery', 'balance', 'balcony', 'bald', 'bale', 'baleful', 'balk', 'ball', 'ballad', 'ballet', 'ballistic', 'balloon', 'ballot', 
        'ballroom', 'balm', 'balmiest', 'balmy', 'baloney', 'balsa', 'balsam', 'banal', 'banana', 'band', 'bandage', 'bandanna', 'bandit', 'bandoleer', 'bandwagon', 
        'bandy', 'bane', 'baneful', 'bang', 'bangle', 'banish', 'banister', 'banjo', 'bank', 'bankroll', 'bankrupt', 'bankruptcy', 'banner', 'banquet', 'banter', 
        'baptism', 'baptize', 'bar', 'barb', 'barbarian', 'barbaric', 'barbarity', 'barbarous', 'barbecue', 'barbed', 'barber', 'bard', 'bare', 'barely', 'barer', 
        'barest', 'bargain', 'barge', 'baritone', 'bark', 'barley', 'barn', 'barnacle', 'barometer', 'baron', 'baroness', 'baronial', 'baroque', 'barque', 'barracks', 
        'barrage', 'barrel', 'barren', 'barrette', 'barricade', 'barrier', 'barring', 'barrio', 'barrister', 'barroom', 'barrow', 'barter', 'basalt', 'base', 'baseball', 
        'baseboard', 'based', 'baseless', 'baseline', 'basement', 'baser', 'bases', 'bash', 'bashful', 'bashfully', 'bashfulness', 'basic', 'basically', 'basil', 'basin', 
        'basis', 'bask', 'basket', 'basketball', 'basque', 'bass', 'basso', 'bassoon', 'bast', 'bastard', 'baste', 'bastion', 'bat', 'batch', 'bate', 
        'bated', 'bath', 'bathe', 'bathhouse', 'bathos', 'bathrobe', 'bathroom', 'bathtub', 'batik', 'bating', 'baton', 'bats', 'battalion', 'batten', 'batter', 
        'battered', 'battering', 'battery', 'batting', 'battle', 'battleax', 'battleaxe', 'battled', 'battlefield', 'battlement', 'battling', 'batty', 'bauble', 'baud', 'baulk', 
        'bauxite', 'bawdy', 'bawl', 'bawling', 'bay', 'bayonet', 'bayou', 'bays', 'bazaar', 'bazooka', 'beach', 'beam', 'bean', 'bear', 'beard', 
        'bearing', 'beast', 'beat', 'beaten', 'beating', 'beautiful', 'beautify', 'beaver', 'became', 'because', 'beckon', 'become', 'bedeck', 'bedevil', 'bedim', 
        'bedlam', 'bedraggle', 'bedridden', 'bedrock', 'bedroom', 'bedside', 'bedspread', 'bee', 'beech', 'beef', 'beefed', 'beefy', 'beehive', 'been', 'beep', 
        'beer', 'beeswax', 'beet', 'beetle', 'befall', 'befit', 'befitting', 'befog', 'befool', 'before', 'beforehand', 'befriend', 'befuddle', 'beg', 'begat', 
        'beget', 'beggar', 'beggary', 'begin', 'beginner', 'beginning', 'begone', 'begonia', 'begot', 'begotten', 'begrudge', 'beguile', 'begun', 'behalf', 'behave', 
        'behaving', 'behavior', 'behead', 'behemoth', 'behest', 'behind', 'behold', 'beholden', 'beholder', 'beholding', 'behoove', 'beige', 'being', 'belabor', 'belated', 
        'belatedly', 'belch', 'beleaguer', 'belfry', 'belie', 'belief', 'believable', 'believe', 'believer', 'believing', 'belittle', 'bell', 'bellboy', 'belle', 'bellied', 
        'bellies', 'belligerence', 'belligerent', 'bellow', 'bellows', 'belly', 'belong', 'belonged', 'belonging', 'belongs', 'beloved', 'below', 'belt', 'belted', 'belting', 
        'belts', 'bemire', 'bemoan', 'bemuse', 'bench', 'bend', 'bended', 'bender', 'bending', 'beneath', 'benediction', 'benefactor', 'benefactress', 'beneficial', 'beneficiary', 
        'benefit', 'benefited', 'benefiting', 'benefits', 'benevolence', 'benevolent', 'benign', 'benignity', 'bent', 'bequeath', 'bequest', 'berate', 'bereave', 'bereaved', 'bereft', 
        'beret', 'berg', 'berry', 'berth', 'beseech', 'beseem', 'beset', 'besetting', 'beside', 'besides', 'besiege', 'besmear', 'besmirch', 'besom', 'besot', 
        'besotted', 'bespangle', 'bespatter', 'bespeak', 'bespoken', 'bespurt', 'best', 'bestial', 'bestiality', 'bestir', 'bestow', 'bestrew', 'bestridden', 'bestride', 'bet', 
        'betake', 'bethink', 'betide', 'betimes', 'betoken', 'betray', 'betrayal', 'betrayer', 'betroth', 'betrothal', 'betrothed', 'better', 'bettered', 'bettering', 'betters', 
        'betting', 'bettor', 'between', 'betwixt', 'bevel', 'beveled', 'beveling', 'bevelled', 'bevelling', 'bevels', 'beverage', 'bevies', 'bevy', 'bewail', 'beware', 
        'bewig', 'bewilder', 'bewildered', 'bewilderment', 'bewitch', 'bewitching', 'beyond', 'bezel', 'bezzle', 'bias', 'biased', 'biases', 'biasing', 'bib', 'bible', 
        'biblical', 'bibliographer', 'bibliography', 'bibliophile', 'bibulous', 'bicameral', 'bicarbonate', 'bicentenary', 'bicentennial', 'biceps', 'bicker', 'bickering', 'bicycle', 'bid', 'biddable', 
        'bidder', 'bidding', 'bide', 'bidet', 'biennial', 'biennium', 'bier', 'bifocal', 'bifurcate', 'bifurcated', 'bifurcation', 'big', 'bigamist', 'bigamous', 'bigamy', 
        'bigness', 'bigot', 'bigoted', 'bigotry', 'bigwig', 'bijou', 'bike', 'bikini', 'bilateral', 'bilberry', 'bile', 'bilge', 'bilingual', 'bilious', 'bilk', 
        'bill', 'billet', 'billeted', 'billeting', 'billets', 'billfold', 'billhead', 'billiard', 'billiards', 'billing', 'billion', 'billionth', 'billow', 'billowing', 'billows', 
        'billowy', 'billy', 'billycock', 'billygoat', 'bilobed', 'bilocation', 'bilocular', 'bilsted', 'bimetal', 'bimetallic', 'bimillenary', 'bimillennial', 'bimontly', 'bin', 'binary', 
        'bind', 'binder', 'bindery', 'binding', 'bindings', 'binds', 'bindweed', 'bine', 'binge', 'bingo', 'binman', 'binominial', 'biochemist', 'biochemistry', 'biodegradable', 
        'biodiversity', 'bioengineering', 'biofeedback', 'biogenesis', 'biogenic', 'biographer', 'biographical', 'biographies', 'biography', 'biological', 'biologically', 'biologies', 'biologist', 'biology', 'biome', 
        'biomechanics', 'biomedical', 'biomedicine', 'biometric', 'biometrics', 'biomorph', 'biomorphic', 'bionics', 'bionomics', 'biopsy', 'biopsychosocial', 'biopy', 'biorhythm', 'bioscience', 'bioscientist', 
        'biosis', 'biosocial', 'biosynthesis', 'biosynthetic', 'biota', 'biotechnology', 'biotic', 'biotin', 'biotite', 'biotope', 'biotype', 'biparous', 'bipartisan', 'bipartisanship', 'bipartite', 
        'biped', 'bipedal', 'bipedaliam', 'bipinnate', 'biplane', 'bipod', 'bipolar', 'biracial', 'biradial', 'biramous', 'birch', 'bird', 'birdbrain', 'birdbrained', 'birdcage', 
        'birdcall', 'birdie', 'birdied', 'birdieing', 'birdies', 'birdlime', 'birdman', 'birds', 'birdseed', 'birdseye', 'birdwatch', 'birdwatcher', 'birefringence', 'birefringent', 'bireme', 
        'biretta', 'birk', 'birl', 'birler', 'birling', 'biro', 'birr', 'birth', 'birthday', 'birthed', 'birthing', 'birthless', 'birthmark', 'birthmother', 'birthname', 
        'birthplace', 'birthrate', 'birthright', 'births', 'birthstone', 'biryani', 'bis', 'biscuit', 'bise', 'bisect', 'bisected', 'bisecting', 'bisection', 'bisector', 'bishop', 
        'bishopdom', 'bishoped', 'bishopess', 'bishoply', 'bishops', 'bishopship', 'bismuth', 'bison', 'bisque', 'bissextile', 'bistable', 'bistate', 'bister', 'bistered', 'bistro', 
        'bistry', 'bisulfate', 'bisulfide', 'bisulfite', 'bisulfuret', 'bit', 'bitable', 'bitalu', 'bitch', 'bitched', 'bitchery', 'bitches', 'bitchier', 'bitchiest', 'bitchily', 
        'bitchiness', 'bitching', 'bitchy', 'bite', 'biter', 'bites', 'bitesize', 'biteweed', 'biting', 'bitingly', 'bitless', 'bitstock', 'bitten', 'bitter', 'bitterbrush', 
        'bittercress', 'bittered', 'bitterend', 'bitterer', 'bitterest', 'bitterling', 'bitterly', 'bittern', 'bitterness', 'bitternut', 'bitters', 'bittersweet', 'bitterweed', 'bittery', 'bitties', 
        'bittily', 'bittiness', 'bitting', 'bittings', 'bitts', 'bitty', 'bitumen', 'bitumenize', 'bituminization', 'bituminize', 'bituminous', 'bivalence', 'bivalency', 'bivalent', 'bivalve', 
        'bivouac', 'bivouacked', 'bivouacking', 'bivouacs', 'bivvy', 'biweekly', 'bizarre', 'bizarrely', 'bizarreness', 'bizcacha', 'blab', 'blabbed', 'blabber', 'blabbering', 'blabbermouth', 
        'blabbers', 'blabbing', 'blabs', 'black', 'blackamoor', 'blackandblue', 'blackandtan', 'blackandtans', 'blackberry', 'blackbird', 'blackbirds', 'blackboard', 'blackboards', 'blackbody', 'blackbook', 
        'blackbuck', 'blackburnian', 'blackcap', 'blackcock', 'blackcurrant', 'blacked', 'blacken', 'blackened', 'blackening', 'blackens', 'blacker', 'blackest', 'blackface', 'blackfish', 'blackfly', 
        'blackguard', 'blackguardism', 'blackguardly', 'blackguards', 'blacking', 'blackish', 'blackjack', 'blackjacked', 'blackjacking', 'blackjacks', 'blackleg', 'blacklegged', 'blacklegging', 'blackmail', 'blackmailed', 
        'blackmailer', 'blackmailing', 'blackmails', 'blackmarket', 'blackmarketer', 'blackmarketing', 'blackness', 'blackout', 'blackouts', 'blacks', 'blacksmith', 'blacksmithing', 'blacksmiths', 'blacksnake', 'blackstrap', 
        'blackthorn', 'blacktop', 'blacktopped', 'blacktopping', 'blacktops', 'blackwater', 'blackwood', 'blanch', 'blank', 'blare', 'blast', 'blaze', 'bleach', 'bleak', 'bleat', 
        'bleed', 'blemish', 'blend', 'bless', 'blight', 'blind', 'blink', 'bliss', 'blister', 'bloat', 'block', 'blog', 'bloom', 'blossom', 'blot', 
        'blotch', 'blow', 'bluff', 'blunder', 'blunt', 'blur', 'blurt', 'blush', 'boast', 'bob', 'bode', 'boggle', 'boil', 'bolt', 'bomb', 
        'bombard', 'bond', 'bone', 'book', 'boom', 'boost', 'bootleg', 'booze', 'border', 'bore', 'borrow', 'boss', 'botch', 'bother', 'bottle', 
        'bounce', 'bound', 'bow', 'bowl', 'box', 'boycott', 'brace', 'bracket', 'brag', 'braid', 'brain', 'brake', 'branch', 'brand', 'brandish', 
        'brave', 'brawl', 'braze', 'breach', 'bread', 'break', 'breast', 'breathe', 'breed', 'brew', 'brick', 'bridge', 'bridle', 'brief', 'brighten', 
        'brim', 'bring', 'brink', 'brisk', 'bristle', 'broach', 'broadcast', 'broaden', 'broil', 'broker', 'bronze', 'brood', 'brook', 'broom', 'broth', 
        'browse', 'bruise', 'brush', 'bubble', 'buck', 'buckle', 'bud', 'budge', 'budget', 'buff', 'buffer', 'buffet', 'bug', 'build', 'bulge', 
        'bulk', 'bull', 'bulldoze', 'bully', 'bump', 'bunch', 'bundle', 'bungle', 'buoy', 'burden', 'burgle', 'burn', 'burnish', 'burp', 'burrow', 
        'burst', 'bury', 'bush', 'bustle', 'buy', 'buzz', 'bypass', 'cache', 'cackle', 'cage', 'cajole', 'cake', 'calculate', 'calibrate', 'call', 
        'calm', 'calumniate', 'camouflage', 'camp', 'campaign', 'cancel', 'cane', 'canoe', 'canopy', 'cant', 'canvass', 'cap', 'capsize', 'captain', 'captivate', 
        'capture', 'card', 'care', 'careen', 'career', 'caress', 'caricature', 'carouse', 'carp', 'carpet', 'carry', 'cart', 'carve', 'cascade', 'case', 
        'cash', 'cashier', 'cast', 'castigate', 'catalog', 'catalyze', 'catapult', 'catch', 'cater', 'cause', 'caution', 'cave', 'cavort', 'cease', 'cede', 
        'celebrate', 'cement', 'censor', 'censure', 'center', 'centralize', 'certify', 'chafe', 'chaff', 'chain', 'chair', 'chalk', 'challenge', 'chamber', 'champion', 
        'chance', 'change', 'channel', 'chant', 'chap', 'chaperon', 'chapter', 'char', 'characterize', 'charge', 'charm', 'chart', 'charter', 'chase', 'chasten', 
        'chastise', 'chat', 'chatter', 'chauffeur', 'cheap', 'cheat', 'check', 'checkmate', 'cheek', 'cheer', 'cheese', 'cherish', 'chew', 'chide', 'chief', 
        'chill', 'chime', 'chimp', 'chin', 'chip', 'chirp', 'chisel', 'chivvy', 'chlorinate', 'chock', 'choice', 'choir', 'choke', 'chomp', 'choose', 
        'chop', 'choppy', 'chord', 'chore', 'choreograph', 'chortle', 'chorus', 'chose', 'christen', 'chronicle', 'chuck', 'chuckle', 'chug', 'chum', 'chunk', 
        'churn', 'chute', 'cicatrize', 'cipher', 'circulate', 'circumcise', 'circumnavigate', 'circumscribe', 'circumvent', 'cite', 'citify', 'citizenize', 'clack', 'claim', 'clamber', 
        'clamor', 'clamp', 'clang', 'clank', 'clap', 'clarify', 'clash', 'clasp', 'classify', 'clatter', 'claw', 'claws', 'clay', 'clean', 'cleanse', 
        'clear', 'cleat', 'cleave', 'clench', 'clerk', 'click', 'climax', 'climb', 'clinch', 'cling', 'clique', 'cloak', 'clock', 'clog', 'cloister', 
        'clone', 'close', 'clothe', 'cloud', 'clout', 'clove', 'clown', 'club', 'cluck', 'clue', 'clump', 'clumsily', 'clumsy', 'cluster', 'clutch', 
        'clutter', 'coach', 'coalesce', 'coarse', 'coast', 'coat', 'coax', 'cobble', 'cobweb', 'cocoon', 'coddle', 'code', 'codify', 'coerce', 'coexist', 
        'coffer', 'coffin', 'cogitate', 'cognate', 'cohabit', 'cohere', 'coil', 'coin', 'coincide', 'coke', 'collapse', 'collar', 'collate', 'collateral', 'colleague', 
        'collect', 'collide', 'collude', 'colonize', 'color', 'colorize', 'colossal', 'colossus', 'colt', 'column', 'comb', 'combat', 'combine', 'combust', 'come', 
        'comeback', 'comedian', 'comedienne', 'comedy', 'comet', 'comfort', 'comfy', 'comic', 'comical', 'coming', 'comma', 'command', 'commandeer', 'commander', 'commemorate', 
        'commence', 'commend', 'commensurate', 'comment', 'commerce', 'commingle', 'comminute', 'commiserate', 'commiseration', 'commissary', 'commission', 'commissionaire', 'commissioner', 'commit', 'commitment', 
        'committal', 'committed', 'committee', 'committeeman', 'committeewoman', 'commode', 'commodious', 'commodity', 'commodore', 'common', 'commonality', 'commonplace', 'commons', 'commotion', 'communal', 
        'commune', 'communication', 'communicative', 'communique', 'communism', 'communist', 'community', 'commutate', 'commutation', 'commutative', 'commutator', 'commute', 'commuter', 'compact', 'companion', 
        'companionable', 'companionway', 'company', 'comparable', 'comparative', 'compare', 'comparison', 'compartment', 'compass', 'compassion', 'compassionate', 'compatriot', 'compel', 'compendium', 'compensate', 
        'compensation', 'compensatory', 'compete', 'competence', 'competency', 'competent', 'competition', 'competitive', 'competitor', 'compilation', 'compile', 'compiler', 'complacence', 'complacency', 'complacent', 
        'complain', 'complainant', 'complaint', 'complaisant', 'complement', 'complementary', 'complete', 'completely', 'completion', 'complex', 'complexion', 'complexity', 'compliance', 'compliant', 'complicate', 
        'complication', 'complicity', 'compliment', 'complimentary', 'comply', 'component', 'comport', 'compose', 'composed', 'composedly', 'composer', 'composite', 'composition', 'compositor', 'compost', 
        'composure', 'compote', 'compound', 'compounder', 'comprehend', 'comprehensible', 'comprehension', 'comprehensive', 'compress', 'compressibility', 'compressible', 'compression', 'compressor', 'comprise', 'compromise', 
        'compromiser', 'comptroller', 'compunction', 'computable', 'computation', 'compute', 'computer', 'computerize', 'comrade', 'comradeship', 'comte', 'comtesse', 'con', 'conation', 'conative', 
        'concave', 'concavity', 'conceal', 'concealer', 'concealment', 'concede', 'conceit', 'conceited', 'conceivable', 'conceivably', 'conceive', 'concelebrate', 'concelebration', 'concentrate', 'concentrated', 
        'concentration', 'concentre', 'concentric', 'concentricity', 'concertante', 'concertina', 'concertino', 'concertmaster', 'concertmeister', 'concerto', 'concertos', 'concervation', 'concession', 'concessionaire', 'concessional', 
        'concessionary', 'concessioner', 'conch', 'conches', 'conchiferous', 'conchitis', 'conchoid', 'conchological', 'conchology', 'conchyliology', 'concierge', 'concieve', 'concilable', 'conciliar', 'conciliary', 
        'conciliate', 'conciliation', 'conciliative', 'conciliator', 'conciliatory', 'concise', 'concisely', 'conciseness', 'concision', 'conclave', 'conclude', 'conclusion', 'conclusive', 'conclusively', 'concoct', 
        'concocter', 'concoction', 'concoctor', 'concomitance', 'concomitancy', 'concomitant', 'concomitantly', 'concord', 'concordable', 'concordance', 'concordant', 'concordat', 'concourse', 'concrete', 'concretely', 
        'concreteness', 'concretion', 'concretionary', 'concretism', 'concretist', 'concretive', 'concretized', 'concretizes', 'concretizing', 'concubinage', 'concubinary', 'concubine', 'conculcate', 'conculcation', 'conculcator', 
        'concupiscence', 'concupiscency', 'concupiscent', 'concupiscible', 'concur', 'concurrence', 'concurrency', 'concurrent', 'concurrently', 'concurring', 'concurs', 'concuss', 'concussion', 'concussive', 'pinnacle'
    ],
    // emotions: 481 words
    emotions: [
        'abandoned', 'abashed', 'abated', 'able', 'abloom', 'abode', 'abrupt', 'absent', 'absorbed', 'abstaining', 'abstinent', 'absurd', 'abused', 'abusive', 'abuzz', 
        'abysmal', 'abyss', 'academic', 'accelerated', 'accented', 'accepted', 'acclaimed', 'accommodating', 'accomplished', 'accordant', 'accounting', 'accrued', 'accused', 'accustomed', 'acerbic', 
        'aching', 'acidic', 'acne-ridden', 'acquainted', 'acquiescent', 'acquisitive', 'acrid', 'acrimonious', 'acrobatic', 'actionable', 'activated', 'active', 'activist', 'actualized', 'acute', 
        'acutely', 'adamant', 'adaptable', 'adapted', 'adaptive', 'addicted', 'addictive', 'additional', 'additionally', 'addlepated', 'addressed', 'adequate', 'adequately', 'adherent', 'adhesive', 
        'adjacent', 'adjudged', 'adjunct', 'adjustable', 'adjusted', 'adjutant', 'admirable', 'admiral', 'admired', 'admiring', 'admissible', 'admitted', 'admittedly', 'admixed', 'admonished', 
        'admonishing', 'adolescent', 'adorable', 'adored', 'adoring', 'adorned', 'adorningly', 'adrift', 'adroit', 'adroitly', 'adsorbing', 'adsorptive', 'adult', 'adulterate', 'adulterated', 
        'adultery', 'adultly', 'adultness', 'advance', 'advanced', 'advancing', 'advantage', 'advantageous', 'advantageously', 'advantagingly', 'advent', 'adventious', 'adventitious', 'adventures', 'adventurous', 
        'adventurously', 'adverbial', 'adversarial', 'adversary', 'adverse', 'adversely', 'adversity', 'advert', 'advertent', 'advertently', 'advertised', 'advertiser', 'advertising', 'advices', 'advisability', 
        'advisable', 'advisably', 'advised', 'advisedly', 'advisee', 'adviser', 'advisor', 'advisory', 'advocacy', 'advocate', 'advocated', 'advocatee', 'advocateless', 'advocateship', 'aegis', 
        'aeon', 'aerial', 'aerially', 'aerified', 'aeriform', 'aeriness', 'aerobatic', 'aerobe', 'aerobic', 'aerobics', 'aerobium', 'aerodrome', 'aerodynamic', 'aerodynamically', 'aerodynamics', 
        'aerodynamist', 'aerodyne', 'aerofoil', 'aerogram', 'aerogramme', 'aerographic', 'aerographically', 'aerography', 'aerolite', 'aerolitic', 'aerological', 'aerologist', 'aerology', 'aeromagnetic', 'aeromancer', 
        'aeromancy', 'aeromechanical', 'aeromechanics', 'aeromedicine', 'aerometer', 'aerometric', 'aerometrically', 'aerometry', 'aeronaut', 'aeronautic', 'aeronautical', 'aeronautically', 'aeronautics', 'aerophagia', 'aerophagic', 
        'aerophagist', 'aerophane', 'aerophany', 'aerophile', 'aerophobe', 'aerophobia', 'aerophobic', 'aerophone', 'aerophonic', 'aerophonically', 'aerophonics', 'aerophony', 'aerophyte', 'aerophytic', 'aerophytical', 
        'aerophytically', 'aerophytism', 'aerophytonomy', 'aeroplane', 'aeroplaning', 'aeroplankton', 'aeroplans', 'aerosol', 'aerosolization', 'aerosols', 'aerosphere', 'aerospheric', 'aerospherical', 'aerostat', 'aerostatic', 
        'aerostatical', 'aerostatically', 'aerostatician', 'aerostatics', 'aerostation', 'aerostats', 'aerotechnical', 'aerotechnics', 'aerotherapeutic', 'aerotherapeutics', 'aerotherapist', 'aerotherapy', 'aerothermal', 'aerothermic', 'aerotics', 
        'aerotitis', 'aerotoluidine', 'aerotransport', 'aerotype', 'aerotypy', 'aeruginose', 'aeruginosity', 'aeruginous', 'aery', 'afraid', 'agitated', 'aimless', 'alert', 'amateur', 'angry', 
        'anxious', 'apathetic', 'appreciated', 'arrogant', 'artificial', 'ashamed', 'attentive', 'authentic', 'betrayed', 'blissful', 'bored', 'bright', 'brilliant', 'broken', 'calculated', 
        'callous', 'calm', 'capable', 'cautious', 'chaotic', 'cherished', 'clear', 'clever', 'closed', 'committed', 'compassionate', 'competent', 'complete', 'confident', 'confused', 
        'conservative', 'considerate', 'content', 'contrived', 'courageous', 'cowardly', 'crude', 'cruel', 'crushed', 'cultured', 'cynical', 'decisive', 'dedicated', 'defeated', 'deflated', 
        'delighted', 'demotivated', 'depressed', 'despairing', 'determined', 'devalued', 'devastated', 'dim', 'disappointed', 'discontent', 'discouraged', 'disgusted', 'dishonest', 'dismayed', 'displeased', 
        'disposable', 'disrespected', 'distracted', 'doubtful', 'downcast', 'drained', 'driven', 'drowsy', 'dull', 'earnest', 'ecstatic', 'educated', 'effective', 'efficient', 'empathetic', 
        'empty', 'enchanted', 'endangered', 'energetic', 'energized', 'enthusiastic', 'envious', 'excited', 'excluded', 'exhilarated', 'experienced', 'expert', 'fake', 'false', 'flexible', 
        'flippant', 'focused', 'foggy', 'foolish', 'forced', 'frantic', 'frustrated', 'fulfilled', 'gentle', 'genuine', 'gifted', 'grateful', 'guilty', 'halfhearted', 'happy', 
        'harsh', 'heartbroken', 'hesitant', 'hollow', 'honest', 'hopeful', 'hopeless', 'horrified', 'humble', 'ignorant', 'important', 'impulsive', 'inattentive', 'incapable', 'included', 
        'incompetent', 'inconsiderate', 'indecisive', 'indifferent', 'ineffective', 'inefficient', 'inexperienced', 'insecure', 'insignificant', 'insincere', 'inspired', 'intelligent', 'interested', 'jealous', 'joyful', 
        'kind', 'knowledgeable', 'lonely', 'loved', 'loyal', 'lucid', 'lukewarm', 'manufactured', 'meaningful', 'meaningless', 'mellow', 'miserable', 'misunderstood', 'modest', 'motivated', 
        'muddled', 'naive', 'natural', 'neglected', 'nervous', 'obtuse', 'open', 'optimistic', 'organic', 'paranoid', 'passionate', 'peaceful', 'pessimistic', 'pleased', 'powerful', 
        'powerless', 'pretend', 'productive', 'professional', 'proficient', 'protected', 'proud', 'purposeful', 'purposeless', 'real', 'refined', 'rejected', 'relieved', 'repulsed', 'resentful', 
        'resolute', 'respected', 'rigid', 'rough', 'sad', 'safe', 'sarcastic', 'satisfied', 'serene', 'sharp', 'simple', 'sincere', 'skilled', 'sophisticated', 'spontaneous', 
        'stable', 'stressed', 'stubborn', 'stupid', 'successful', 'supportive', 'suspicious', 'sympathetic', 'talented', 'tender', 'tense', 'thoughtful', 'thoughtless', 'thrilled', 'tired', 
        'triumphant', 'trusting', 'turbulent', 'unable', 'unaccomplished', 'uncertain', 'uncommitted', 'uncultured', 'understood', 'uneducated', 'ungifted', 'ungrateful', 'unmotivated', 'unproductive', 'unprofessional', 
        'unproficient', 'unsatisfied', 'unskilled', 'unsuccessful', 'unsupportive', 'untalented', 'uplifted', 'vain', 'valued', 'victorious', 'vulnerable', 'whole', 'wholehearted', 'wise', 'witty', 
        'worried'
    ],
    // adjectives: 537 words
    adjectives: [
        'abhorrent', 'abnormal', 'abominable', 'abundant', 'accomplished', 'acerbic', 'aching', 'acidic', 'acquainted', 'acrid', 'acting', 'active', 'actual', 'acute', 'adamant', 
        'adaptable', 'adapted', 'addicted', 'adequate', 'adjacent', 'adjunct', 'adjustable', 'adjusted', 'admirable', 'admiring', 'admonishing', 'adolescent', 'adoptable', 'adopted', 'adoptive', 
        'adorable', 'adored', 'adoring', 'adorned', 'adrift', 'adroit', 'adsorbing', 'adult', 'adulterable', 'adulterate', 'adulterated', 'adulterine', 'adultery', 'adultly', 'adultness', 
        'advanced', 'advancing', 'advantage', 'advantaged', 'advantageous', 'advantageously', 'advent', 'adventious', 'adventitious', 'adventive', 'adventureful', 'adventuresome', 'adventurous', 'adventurously', 'adverbial', 
        'adverbially', 'adversarial', 'adversary', 'adverse', 'adversely', 'adversity', 'advertent', 'advertently', 'advertised', 'advertising', 'advisability', 'advisable', 'advisably', 'advised', 'advisedly', 
        'advisee', 'adviser', 'advisor', 'advisory', 'advocacy', 'advocated', 'advocatee', 'advocateless', 'advocates', 'advocateship', 'aerated', 'aerating', 'aeration', 'aerobic', 'aerobically', 
        'aerobious', 'aerobius', 'aerodactyl', 'aerodynamic', 'aerodynamical', 'aerodynamically', 'aerodyne', 'aerodynes', 'aerogastric', 'aerogel', 'aerogenic', 'aerogenically', 'aerogenous', 'aerogenously', 'aerographic', 
        'aerographically', 'aerolitic', 'aerologic', 'aerologically', 'aeromantic', 'aeromechanical', 'aeromedicinal', 'aerometric', 'aerometrically', 'aeronauric', 'aeronautic', 'aeronautical', 'aeronautically', 'aerophagic', 'agitated', 
        'agreeable', 'ahead-of-the-curve', 'amazing', 'ample', 'amusing', 'ancient', 'antagonistic', 'apparent', 'appealing', 'archaic', 'atrocious', 'attractive', 'atypical', 'awesome', 'awful', 
        'bad', 'barren', 'basic', 'beautiful', 'beneficial', 'big', 'bizarre', 'blurry', 'boring', 'bounded', 'boundless', 'bright', 'brilliant', 'brittle', 'broad', 
        'broken', 'busy', 'captivating', 'chaotic', 'charming', 'clean', 'clear', 'clichéd', 'coarse', 'cold', 'collaborative', 'colorful', 'committed', 'common', 'compelling', 
        'competitive', 'complete', 'complex', 'compliant', 'complicated', 'concealed', 'concordant', 'confined', 'conflictual', 'conspicuous', 'constant', 'constructive', 'contained', 'contemporary', 'contemptible', 
        'conventional', 'convoluted', 'cool', 'cooperative', 'copious', 'covert', 'crisp', 'crowded', 'curious', 'current', 'cutting-edge', 'damaged', 'dangerous', 'dark', 'dedicated', 
        'deep', 'defeated', 'defiant', 'defined', 'delicate', 'delightful', 'dense', 'dependable', 'despicable', 'destructive', 'detrimental', 'devoted', 'dim', 'direct', 'dirty', 
        'disagreeable', 'discordant', 'disengaging', 'disgusting', 'disloyal', 'disobedient', 'displeasing', 'distinct', 'distracting', 'divine', 'docile', 'done', 'drab', 'dreadful', 'dull', 
        'durable', 'dynamic', 'elaborate', 'elementary', 'empty', 'enclosed', 'energetic', 'engaging', 'entertaining', 'essential', 'eternal', 'evident', 'excellent', 'exceptional', 'excessive', 
        'exciting', 'explicit', 'exposed', 'exquisite', 'extraordinary', 'faded', 'failed', 'faithful', 'fantastic', 'fascinating', 'feeble', 'fertile', 'fickle', 'fine', 'finished', 
        'finite', 'firm', 'flawed', 'fleeting', 'flexible', 'fluid', 'formulaic', 'fragile', 'fragmented', 'fresh', 'friendly', 'fruitful', 'frustrating', 'fulfilling', 'full', 
        'functional', 'fundamental', 'funny', 'fuzzy', 'generative', 'gentle', 'ghastly', 'glaring', 'gleaming', 'glorious', 'glowing', 'good', 'gorgeous', 'gratifying', 'grave', 
        'great', 'groundbreaking', 'gruesome', 'hackneyed', 'halfhearted', 'handsome', 'hard', 'harmful', 'harmonious', 'hazy', 'heavenly', 'heavy', 'helpful', 'hidden', 'hideous', 
        'hilarious', 'horrible', 'horrid', 'hot', 'ideal', 'immaculate', 'impenetrable', 'imperceptible', 'imperfect', 'implicit', 'inactive', 'incomplete', 'inconspicuous', 'indifferent', 'indirect', 
        'inferior', 'infertile', 'infinite', 'innovative', 'inoperable', 'insecure', 'intact', 'interesting', 'intricate', 'invisible', 'kind', 'large', 'lasting', 'lazy', 'lethargic', 
        'light', 'limited', 'liquid', 'lively', 'loathsome', 'loose', 'losing', 'loud', 'lovely', 'loyal', 'lucrative', 'luminous', 'magnificent', 'marvelous', 'meager', 
        'mean', 'mediocre', 'mighty', 'minimal', 'modern', 'monochromatic', 'monotonous', 'mundane', 'murky', 'muted', 'narrow', 'new', 'nice', 'noisy', 'nonfunctional', 
        'normal', 'noticeable', 'novel', 'obedient', 'obscure', 'obvious', 'occupied', 'odd', 'old', 'opaque', 'open', 'operable', 'ordinary', 'original', 'ornate', 
        'outdated', 'outstanding', 'overt', 'overused', 'peaceful', 'peculiar', 'perfect', 'permanent', 'pioneering', 'pleasant', 'pleasing', 'plentiful', 'poor', 'powerful', 'predictable', 
        'pretty', 'pristine', 'productive', 'profitable', 'protected', 'pure', 'quiet', 'radiant', 'rare', 'relaxed', 'reliable', 'repelling', 'repugnant', 'restricted', 'revolting', 
        'revolutionary', 'rewarding', 'rigid', 'robust', 'rough', 'routine', 'safe', 'satisfying', 'scanty', 'scarce', 'secure', 'serene', 'serious', 'shadowy', 'shaky', 
        'shallow', 'sharp', 'sheltered', 'shining', 'silent', 'simple', 'slack', 'small', 'smooth', 'soft', 'soiled', 'solid', 'sophisticated', 'sound', 'sparse', 
        'special', 'splendid', 'spoiled', 'spotless', 'stable', 'stale', 'standard', 'static', 'steadfast', 'steady', 'stereotypical', 'stiff', 'still', 'straightforward', 'strange', 
        'strong', 'stunning', 'sturdy', 'subtle', 'superb', 'superior', 'supple', 'tainted', 'tame', 'tarnished', 'taut', 'tedious', 'temporary', 'tense', 'terrible', 
        'thick', 'thin', 'thrilling', 'tight', 'tiny', 'tired', 'traditional', 'trailblazing', 'tranquil', 'transient', 'translucent', 'transparent', 'trembling', 'triumphant', 'trustworthy', 
        'turbulent', 'typical', 'ugly', 'unaccomplished', 'unappealing', 'unattractive', 'uncommitted', 'uncomplicated', 'unconfined', 'uncontained', 'undefined', 'undependable', 'understated', 'undone', 'unfaithful', 
        'unfinished', 'unfriendly', 'unfulfilling', 'unhelpful', 'unique', 'unkind', 'unlimited', 'unoccupied', 'unpleasant', 'unproductive', 'unprofitable', 'unreliable', 'unrestricted', 'unrewarding', 'unruly', 
        'unsatisfying', 'unsound', 'unstable', 'untrustworthy', 'unusual', 'useful', 'useless', 'vacant', 'variable', 'vibrant', 'victorious', 'vigorous', 'vile', 'violent', 'visible', 
        'vivid', 'vulnerable', 'warm', 'weak', 'weird', 'whole', 'wide', 'wild', 'winning', 'wonderful', 'working', 'wretched'
    ],
    // nouns: 664 words
    nouns: [
        'ability', 'abnormality', 'abolition', 'abortion', 'abrasion', 'abreaction', 'abscess', 'absence', 'absentia', 'absinthe', 'absoluteness', 'absolutes', 'absolution', 'absolutism', 'absolutist', 
        'absolutization', 'absolutory', 'absolver', 'absolvment', 'absorb', 'absorbable', 'absorbancy', 'absorbent', 'absorbents', 'absorber', 'absorbers', 'absorptance', 'absorption', 'absorptions', 'absorptive', 
        'absorptively', 'absorptiveness', 'absorptivity', 'abstainer', 'abstainers', 'abstaining', 'abstainment', 'abstemious', 'abstemiously', 'abstemiousness', 'abstemium', 'abstentia', 'abstention', 'abstentionism', 'abstentionist', 
        'abstentions', 'abstentious', 'abstentiously', 'abstentiousness', 'abstentism', 'abstentuousness', 'absterge', 'abstersion', 'abstersive', 'abstersively', 'abstersiveness', 'abstractability', 'abstractable', 'abstracted', 'abstractedly', 
        'abstractedness', 'abstracter', 'abstracters', 'abstractibility', 'abstractible', 'abstraction', 'abstractionism', 'abstractionisms', 'abstractionist', 'abstractionistic', 'abstractionists', 'abstractions', 'abstractive', 'abstractively', 'abstractiveness', 
        'abstractivity', 'abstractly', 'abstractness', 'abstracts', 'abstractual', 'abstractualism', 'abstractualisms', 'abstractualist', 'abstractualistic', 'abstractualists', 'abstractuality', 'abstractualization', 'abstractualizations', 'abstractualize', 'abstractualized', 
        'abstractualizer', 'abstractualizers', 'abstractualizes', 'abstractualizing', 'abstractually', 'abstractum', 'abstracturer', 'abstruse', 'abstrusely', 'abstruseness', 'abstrusities', 'abstrusity', 'abstuosity', 'abstuously', 'abstuousness', 
        'absuation', 'accident', 'accomplishment', 'achievement', 'action', 'action figure', 'actor', 'adult', 'adventure', 'advice', 'afternoon', 'age', 'air', 'airplane', 'alliance', 
        'alternative', 'ambition', 'angel', 'animal', 'anniversary', 'answer', 'apple', 'architect', 'argument', 'armor', 'art', 'artist', 'aspiration', 'asteroid', 'attack', 
        'attitude', 'aunt', 'avalanche', 'avenue', 'award', 'baby', 'ball', 'ballet', 'banana', 'bar', 'bartender', 'bat', 'beach', 'bed', 'bed and breakfast', 
        'beginning', 'behavior', 'belief', 'bicycle', 'bike', 'bird', 'birth', 'birthday', 'black hole', 'blessing', 'boat', 'bomb', 'book', 'boss', 'boulevard', 
        'boy', 'bravery', 'bread', 'bridge', 'brother', 'building', 'bullet', 'bus', 'cafe', 'cake', 'candy', 'canoe', 'car', 'cat', 'ceiling', 
        'celebration', 'century', 'ceremony', 'certainty', 'chair', 'chance', 'change', 'character', 'chat', 'chef', 'child', 'children', 'chocolate', 'choice', 'church', 
        'cinema', 'city', 'class', 'clinic', 'cloud', 'club', 'coach', 'coffee', 'colleague', 'college', 'comet', 'comfort', 'command', 'competition', 'computer', 
        'concert', 'conclusion', 'conduct', 'conference', 'confidence', 'consequence', 'continent', 'conversation', 'cook', 'cookie', 'couch', 'country', 'courage', 'court', 'cousin', 
        'cowardice', 'coworker', 'creation', 'creativity', 'cruise', 'culture', 'cure', 'curse', 'custom', 'dance', 'danger', 'darkness', 'day', 'death', 'debate', 
        'decade', 'decay', 'decision', 'decline', 'defeat', 'defense', 'demand', 'demon', 'dependence', 'designer', 'desire', 'desk', 'despair', 'dessert', 'determination', 
        'development', 'direction', 'director', 'disaster', 'discomfort', 'discovery', 'discussion', 'disease', 'disgrace', 'doctor', 'dog', 'doll', 'door', 'doubt', 'dream', 
        'drink', 'earth', 'earthquake', 'education', 'effect', 'effort', 'emergency', 'employee', 'employer', 'end', 'enemy', 'energy', 'engineer', 'epoch', 'era', 
        'evening', 'event', 'evil', 'evolution', 'existence', 'experience', 'exploration', 'explosion', 'expression', 'fable', 'fact', 'failure', 'fairy tale', 'faith', 'fall', 
        'family', 'fantasy', 'father', 'fear', 'festival', 'fiction', 'figure', 'finish', 'fire', 'fire station', 'fish', 'flood', 'floor', 'flower', 'food', 
        'foolishness', 'forest', 'fortune', 'fountain', 'freedom', 'friend', 'frown', 'fruit', 'funeral', 'furniture', 'future', 'galaxy', 'game', 'garden', 'gathering', 
        'generation', 'gesture', 'ghost', 'gift', 'girl', 'glory', 'glove', 'goal', 'good', 'gossip', 'grandfather', 'grandmother', 'grandparent', 'grape', 'grief', 
        'growth', 'gun', 'gym', 'habit', 'hamburger', 'hazard', 'healing', 'helmet', 'highway', 'history', 'holiday', 'home', 'honor', 'hope', 'hospital', 
        'hotel', 'hour', 'house', 'human', 'hunger', 'hurricane', 'ice cream', 'ignorance', 'illness', 'image', 'imagination', 'impact', 'independence', 'influence', 'injury', 
        'inquiry', 'inspiration', 'invention', 'island', 'jail', 'job', 'joke', 'journey', 'joy', 'judge', 'judgment', 'juice', 'keyboard', 'kid', 'kids', 
        'knowledge', 'labor', 'lake', 'lamp', 'language', 'laughter', 'lawyer', 'learning', 'lecture', 'legend', 'letter', 'liberty', 'library', 'lie', 'life', 
        'light', 'lightning', 'loss', 'luck', 'mall', 'man', 'manner', 'market', 'match', 'meat', 'medal', 'medicine', 'meeting', 'memory', 'meteor', 
        'milk', 'minute', 'mission', 'moment', 'monitor', 'month', 'monument', 'moon', 'morning', 'mosque', 'motel', 'mother', 'motorcycle', 'mountain', 'mouse', 
        'movement', 'movie', 'museum', 'music', 'musician', 'myth', 'need', 'neighbor', 'net', 'night', 'nightmare', 'novel', 'number', 'nurse', 'objective', 
        'ocean', 'office', 'officer', 'opera', 'opinion', 'opportunity', 'option', 'orange', 'order', 'origin', 'outcome', 'pain', 'painting', 'paper', 'parent', 
        'park', 'party', 'past', 'pasta', 'path', 'patient', 'peace', 'pen', 'people', 'period', 'persistence', 'person', 'personality', 'pharmacy', 'phone', 
        'picture', 'pizza', 'planet', 'plant', 'play', 'player', 'pleasure', 'police', 'police station', 'possibility', 'power', 'practice', 'present', 'presentation', 'prevention', 
        'prison', 'prize', 'probability', 'producer', 'progress', 'protection', 'province', 'pub', 'puzzle', 'query', 'question', 'racket', 'radio', 'rain', 'reaction', 
        'reality', 'recommendation', 'recovery', 'region', 'relative', 'reliance', 'religion', 'remedy', 'reputation', 'request', 'resilience', 'resort', 'response', 'restaurant', 'result', 
        'revolution', 'rice', 'riddle', 'risk', 'river', 'road', 'rocket', 'roof', 'room', 'route', 'rumor', 'safety', 'salad', 'sandwich', 'school', 
        'screen', 'sculpture', 'season', 'second', 'secret', 'security', 'selection', 'seminar', 'sentence', 'server', 'shame', 'ship', 'shopping center', 'show', 'sickness', 
        'sister', 'skill', 'sky', 'skyscraper', 'smile', 'snow', 'soldier', 'sorrow', 'soul', 'sound', 'soup', 'space', 'spacecraft', 'speech', 'spirit', 
        'spirituality', 'sport', 'spring', 'star', 'start', 'state', 'statue', 'store', 'storm', 'story', 'stranger', 'strawberry', 'street', 'strength', 'student', 
        'subway', 'success', 'suggestion', 'summer', 'sun', 'surrender', 'sword', 'synagogue', 'table', 'tale', 'talent', 'talk', 'task', 'tea', 'teacher', 
        'teaching', 'team', 'tears', 'teen', 'teenager', 'television', 'temple', 'theater', 'thirst', 'threat', 'thunder', 'time', 'tornado', 'tournament', 'town', 
        'toy', 'tradition', 'train', 'training', 'transformation', 'travel', 'treatment', 'treaty', 'tree', 'trip', 'trophy', 'truck', 'trust', 'truth', 'tunnel', 
        'uncle', 'understanding', 'universe', 'university', 'valley', 'vegetable', 'victory', 'video', 'village', 'voice', 'waiter', 'wall', 'want', 'war', 'water', 
        'way', 'weakness', 'weapon', 'weather', 'wedding', 'week', 'wind', 'window', 'winter', 'wisdom', 'wish', 'woman', 'word', 'work', 'workshop', 
        'world', 'writer', 'yacht', 'year'
    ],
    // commonPhrases: 157 words
    commonPhrases: [
        'a bit much', 'a far cry', 'a piece of cake', 'a tough row to hoe', 'ace in the hole', 'acid test', 'add insult to injury', 'all things considered', 'all washed up', 'at a loose end', 'at odds', 'at the drop of a hat', 'at wit's end', 'back to square one', 'back to the drawing board', 
        'bad to the bone', 'bald faced liar', 'ballpark figure', 'barking up the wrong tree', 'bat out of hell', 'be all and end all', 'beat a dead horse', 'beat around the bush', 'been there done that', 'behind the eight ball', 'bend over backwards', 'benefit of the doubt', 'bent out of shape', 'best of luck', 'bet your bottom dollar', 
        'between a rock and a hard place', 'beyond a shadow of a doubt', 'beyond the pale', 'big picture', 'bigger they are the harder they fall', 'bird in the hand', 'birds of a feather flock together', 'bite the bullet', 'bite the dust', 'black as coal', 'black as night', 'black market', 'black sheep', 'blank check', 'blank slate', 
        'bleed dry', 'blind ambition', 'blind as a bat', 'blind leading the blind', 'block party', 'blood diamond', 'blood is thicker than water', 'blow hot and cold', 'blow off steam', 'blow your own horn', 'blushing bride', 'board of directors', 'body and soul', 'boils down to', 'bolt from the blue', 
        'bone to pick', 'bored stiff', 'bored to tears', 'break a leg', 'break the bank', 'break the ice', 'brick and mortar', 'broken record', 'brought back to reality', 'bubble burst', 'buck stops here', 'buckle down', 'built to last', 'bull market', 'burn the midnight oil', 
        'burning the candle at both ends', 'burst your bubble', 'bury the hatchet', 'busy as a bee', 'by and large', 'call it a day', 'calm before the storm', 'calm down', 'can of worms', 'cannot cut the mustard', 'cannot hold a candle to', 'case in point', 'catch my drift', 'caught between a rock and a hard place', 'caught red-handed', 
        'cease and desist', 'center of attention', 'change of heart', 'change of pace', 'changing of the guard', 'chase your tail', 'cheap shot', 'cheat death', 'check out', 'checkmate', 'chew on that', 'chick magnet', 'chief suspect', 'chill out', 'chilly willy', 
        'chin up', 'chip on his shoulder', 'chips are down', 'chisel away at', 'choice of words', 'circle the wagons', 'circling the drain', 'circumstantial evidence', 'city limits', 'civil disobedience', 'civil service', 'claim to fame', 'clam up', 'clamor for', 'clamped down on', 
        'clash of the titans', 'class act', 'class conscious', 'class warfare', 'classic case', 'classify as', 'classify information', 'classy dresser', 'clean bill of health', 'clean break', 'clean slate', 'clean sweep', 'clean up', 'cleaner than a whistle', 'cleaning house', 
        'cleanly separated', 'clear as a bell', 'clear as crystal', 'clear as day', 'clear as mud', 'clear channel', 'clear conscience', 'clear cut', 'clear heads', 'clear line of succession', 'clear majority', 'clear signal', 'clear the air', 'clear the decks', 'clear thinking', 
        'clear view', 'cleared for takeoff', 'clearer picture', 'clearest water', 'clearing house', 'clearness of vision', 'clearway'
    ],
    // responses: 495 words
    responses: [
        'absolutely', 'ad infinitum', 'ad nauseam', 'after all', 'agreed', 'ahem', 'all in all', 'all the same', 'all things considered', 'allegedly', 'alright', 'although', 'analogously', 'and so forth', 'and so on', 
        'apparently', 'arguably', 'as a consequence', 'as a contrast', 'as a result', 'as expected', 'as far as i know', 'as far as i'm aware', 'as i understand it', 'as it happens', 'as it were', 'as much as i know', 'as you say', 'ask me', 'assuming', 
        'assuredly', 'at all costs', 'at heart', 'at its core', 'at last', 'at long last', 'at present', 'at the moment', 'at the same time', 'at this juncture', 'at this point', 'at your service', 'awful', 'aye', 'bah', 
        'basically', 'be my guest', 'be that as it may', 'beats me', 'because of', 'been better', 'been there', 'been worse', 'before', 'before long', 'being that', 'believe it or not', 'best of luck', 'better luck next time', 'better yet', 
        'beyond doubt', 'beyond my scope', 'beyond question', 'big deal', 'bluntly', 'bold claim', 'bravo', 'break a leg', 'breakthrough', 'briefly', 'bring it', 'broadly speaking', 'brutal', 'buckle down', 'bull market', 
        'bullseye', 'burn', 'burning question', 'bury the hatchet', 'bush league', 'bushed', 'business as usual', 'bust a move', 'busted', 'but', 'but seriously', 'butter up', 'by and large', 'by any means necessary', 'by chance', 
        'by coincidence', 'by hook or by crook', 'by the same token', 'by the way', 'c'est la vie', 'calm down', 'can't say i disagree', 'candidly', 'careful there', 'catch my drift', 'categorically', 'caught that', 'ceaselessly', 'center of attention', 'certainly', 
        'checkmate', 'chef's kiss', 'cherry picked', 'chew on that', 'chill out', 'chin up', 'choice words', 'circle back', 'circuitously', 'clammed up', 'clamor for', 'clapping', 'clean slate', 'clear as day', 'clear the air', 
        'clearly', 'clever move', 'clip-on', 'clockwise', 'close but no cigar', 'close call', 'close enough', 'close the loop', 'closer inspection', 'closest match', 'closing arguments', 'closing ceremony', 'closing in', 'closing remarks', 'closing statement', 
        'closure', 'clot', 'cloth', 'clothe', 'clothed', 'clothespins', 'clothing', 'clotted', 'clotting', 'cloud cover', 'cloud nine', 'cloudy', 'clout', 'clove', 'cloven', 
        'clover', 'cloverleaf', 'clown around', 'clowned', 'clowning', 'clowns', 'cloying', 'club', 'clubbed', 'clubbing', 'clubfoot', 'clubhouse', 'clubman', 'clubroom', 'clubs', 
        'cluck', 'clucked', 'clucking', 'clucks', 'clue', 'clued', 'clueless', 'clues', 'cluing', 'cluing in', 'clump', 'clumped', 'clumping', 'clumpish', 'clumps', 
        'clumpy', 'clumsily', 'clumsiness', 'clumsy', 'clung', 'clunk', 'clunked', 'clunker', 'clunking', 'clunks', 'clunky', 'clutter', 'cluttered', 'cluttering', 'clutters', 
        'cluttery', 'clyde', 'clydesdale', 'clypeal', 'clypeate', 'clypei', 'clypeus', 'clysma', 'clysmata', 'clyster', 'cnidaria', 'cnidarian', 'cnidarians', 'coadapted', 'coadaption', 
        'coadaptions', 'coadaptive', 'coadaptively', 'coadapts', 'come hell or high water', 'come to think of it', 'come what may', 'completely', 'consequently', 'considering', 'conspicuously', 'continually', 'continuously', 'contrarily', 'contrastingly', 
        'conversely', 'correct me if i'm wrong', 'correspondingly', 'could be', 'currently', 'definitely', 'directly', 'distinctly', 'doggedly', 'doubtful', 'doubtless', 'due to', 'earlier', 'endlessly', 'entirely', 
        'essentially', 'et cetera', 'etc', 'etcetera', 'even if', 'even though', 'eventually', 'evidently', 'except', 'except that', 'explicitly', 'fair point', 'fairly', 'finally', 'for', 
        'for example', 'for instance', 'for now', 'for sure', 'for the reason that', 'for the time being', 'formerly', 'fortunately', 'frankly', 'from my perspective', 'from what i hear', 'from what i understand', 'fully', 'fundamentally', 'generally speaking', 
        'given that', 'good point', 'got me', 'granted', 'happily', 'hard to say', 'hence', 'heretofore', 'hitherto', 'honestly', 'however', 'i assume', 'i believe', 'i feel you', 'i get it', 
        'i guess', 'i hear you', 'i just realized', 'i just remembered', 'i see what you mean', 'i suppose', 'i think', 'i understand', 'if i recall correctly', 'if i'm not mistaken', 'if memory serves', 'if you ask me', 'if you will', 'iffy', 'implicitly', 
        'in a manner of speaking', 'in a nutshell', 'in a roundabout way', 'in a way', 'in brief', 'in case', 'in consequence', 'in contrast', 'in due time', 'in essence', 'in general', 'in like manner', 'in my book', 'in my experience', 'in my opinion', 
        'in my view', 'in short', 'in summary', 'in the end', 'in the event of', 'in the event that', 'in the interim', 'in the meantime', 'in the same way', 'in the unlikely event that', 'in time', 'inasmuch as', 'indirectly', 'indubitably', 'ineluctably', 
        'inevitably', 'inexorably', 'insofar as', 'insofar as i know', 'inversely', 'it appears', 'it just hit me', 'it looks like', 'it occurs to me', 'it seems', 'it seems like', 'kind of', 'lamentably', 'like', 'likely', 
        'likewise', 'luckily', 'manifestly', 'maybe', 'meanwhile', 'mercifully', 'might', 'nah', 'namely', 'necessarily', 'no clue', 'no doubt', 'no doubt about it', 'no idea', 'nonetheless', 
        'nope', 'not exactly', 'not quite', 'not really', 'notably', 'noticeably', 'obliquely', 'obviously', 'of course', 'okay', 'on account of', 'on balance', 'on the bright side', 'on the condition that', 'on the downside', 
        'on the flip side', 'on the other hand', 'on the upside', 'oppositely', 'ostensibly', 'outright', 'overall', 'owing to', 'palpably', 'partial', 'partially', 'patently', 'perforce', 'perhaps', 'persistently', 
        'personally', 'plainly', 'point blank', 'positively', 'possibly', 'pretty', 'previously', 'probably', 'provided that', 'providentially', 'providing that', 'purportedly', 'quite', 'rain or shine', 'rather', 
        'regrettably', 'relentlessly', 'remarkably', 'reportedly', 'reputedly', 'right now', 'roundaboutly', 'rumor has it', 'sadly', 'save that', 'seeing', 'seeing that', 'seemingly', 'similarly', 'since', 
        'so far', 'so i hear', 'so to speak', 'somewhat', 'sort of', 'speaking of which', 'specifically', 'still', 'straightforwardly', 'strikingly', 'such as', 'supposedly', 'supposing', 'sure', 'surely', 
        'tacitly', 'taking everything into account', 'thankfully', 'that adds up', 'that being said', 'that makes sense', 'that reminds me', 'that said', 'then again', 'therefore', 'thoroughly', 'though', 'through thick and thin', 'thus', 'thus far', 
        'to my knowledge', 'to my mind', 'to no end', 'to sum up', 'to the best of my knowledge', 'to the point', 'totally', 'transparently', 'truthfully', 'ultimately', 'unambiguously', 'unavoidably', 'uncertain', 'unclear', 'undeniably', 
        'unequivocally', 'unfortunately', 'unknown', 'unless', 'unless i'm mistaken', 'unlikely', 'unluckily', 'unmistakably', 'unquestionably', 'unsure', 'until then', 'vice versa', 'what have you', 'what not', 'when all is said and done', 
        'whereas', 'which reminds me', 'while', 'wholly', 'willy nilly', 'without a doubt', 'without question', 'yeah', 'yep', 'yes', 'yet', 'you bet', 'you got me', 'you make a good point', 'you name it'
    ],
    // work: 358 words
    work: [
        'ability', 'absent', 'abstract', 'abundant', 'accelerate', 'accessible', 'accomplice', 'accomplish', 'accomplishment', 'accord', 'account', 'accountable', 'accountant', 'accounting', 'accredit', 
        'accreditation', 'accrual', 'accumulate', 'accuracy', 'accurate', 'accusation', 'accuse', 'achieve', 'achievement', 'acid test', 'acquaint', 'acquaintance', 'acquire', 'acquit', 'acumen', 
        'adapt', 'adaptability', 'adaptable', 'adaptation', 'adapted', 'adapter', 'add', 'addition', 'additional', 'additionally', 'address', 'adequacy', 'adequate', 'adequately', 'adhere', 
        'adhesion', 'adjacent', 'adjoin', 'adjourn', 'adjournment', 'adjudicate', 'adjudication', 'adjudicator', 'adjunct', 'adjust', 'adjustable', 'adjusted', 'adjuster', 'adjustment', 'administer', 
        'administration', 'administrations', 'administrative', 'administratively', 'administrator', 'administrators', 'admirability', 'admirable', 'admirably', 'admiral', 'admirals', 'admiration', 'admire', 'admirer', 'admirers', 
        'admires', 'admiring', 'admiringly', 'admissibility', 'admissible', 'admissibly', 'admission', 'admissions', 'admit', 'admitance', 'admits', 'admittance', 'admittedly', 'admitting', 'admix', 
        'admixture', 'admonish', 'admonished', 'admonisher', 'admonishes', 'admonishing', 'admonishment', 'admonition', 'admonitions', 'admonitor', 'admonitory', 'ado', 'adobe', 'adobes', 'adolescence', 
        'adolescent', 'adolescents', 'adopt', 'adopted', 'adoptee', 'adoptees', 'adopter', 'adopters', 'adopting', 'adoption', 'adoptionism', 'adoptionist', 'adoptions', 'adoptive', 'adoptively', 
        'adopts', 'adorability', 'adorable', 'adorably', 'adoration', 'adorations', 'adore', 'adored', 'adorer', 'adorers', 'adores', 'adoring', 'adoringly', 'adorn', 'adorned', 
        'adorner', 'adorners', 'adorning', 'adorningly', 'adornment', 'adornments', 'adorns', 'adrenal', 'adrenalin', 'adrenaline', 'adrenalines', 'adrenals', 'adrenergic', 'adrenergical', 'adrenergically', 
        'adrenergics', 'adrenochrome', 'adrenosteroid', 'adriatic', 'adrift', 'adroit', 'adroitly', 'adroitness', 'adscititious', 'adscript', 'adscription', 'adsorbate', 'adsorbates', 'adsorbent', 'adsorbents', 
        'adsorbing', 'adsorbs', 'adsorption', 'adsorptions', 'adsorptive', 'adsorptively', 'adsorptiveness', 'adsorptivity', 'adularia', 'adularias', 'adviser', 'advisor', 'analyst', 'assignment', 'auditor', 
        'available', 'barrier', 'bind', 'boardroom', 'boss', 'bottleneck', 'bounded', 'branch', 'branch office', 'break room', 'breakroom', 'bug', 'bullpen', 'business', 'business analyst', 
        'cafeteria', 'calling', 'canteen', 'career', 'catch 22', 'catch-22', 'ceo', 'cfo', 'challenge', 'checkpoint', 'commissary', 'commitment', 'company', 'complexity', 'complication', 
        'conference room', 'confined', 'conglomerate', 'constrained', 'consultant', 'convenient', 'coo', 'corner office', 'corporation', 'craft', 'cto', 'cube', 'cubicle', 'data analyst', 'deadline', 
        'deliverable', 'department', 'desk', 'difficulty', 'dilemma', 'dining room', 'director', 'disadvantage', 'discipline', 'division', 'domain', 'downside', 'drawback', 'duty', 'ease', 
        'easy', 'effortless', 'employee', 'employment', 'enterprise', 'error', 'executive', 'executive suite', 'executive team', 'expert', 'failure', 'field', 'finite', 'firm', 'fix', 
        'foreman', 'generalist', 'glass walled', 'glass-walled', 'glitch', 'hot water', 'hr department', 'human resources', 'hurdle', 'inaccessible', 'inconvenient', 'industry', 'infinite', 'issue', 'jam', 
        'job', 'kitchen', 'leader', 'leadership', 'limited', 'llc', 'lunchroom', 'management', 'manager', 'meeting room', 'milestone', 'mistake', 'multinational', 'obligation', 'obstacle', 
        'occupation', 'office', 'officer', 'open office', 'open plan', 'open-plan', 'operation', 'organization', 'outcome', 'outfit', 'output', 'overseer', 'owner', 'painless', 'partnership', 
        'personnel', 'pickle', 'pitfall', 'plentiful', 'predicament', 'president', 'problem', 'profession', 'project', 'proprietor', 'quandary', 'responsibility', 'restricted', 'result', 'scale up', 
        'scale-up', 'scarce', 'secretary', 'sector', 'setback', 'simple', 'simplicity', 'sole proprietor', 'sole proprietorship', 'sophistication', 'specialist', 'staff', 'startup', 'straightforward', 'success', 
        'supervisor', 'systems analyst', 'task', 'team', 'team leader', 'team member', 'tight spot', 'trade', 'trap', 'treasurer', 'trouble', 'unavailable', 'unbounded', 'unconfined', 'unconstrained', 
        'unicorn', 'unlimited', 'unrestricted', 'venture', 'vice president', 'vice-president', 'vocation', 'war room', 'windowless', 'work', 'workforce', 'workspace', 'workstation'
    ],
    // relationships: 353 words
    relationships: [
        'accompanied', 'accompanier', 'accompaniers', 'accompanies', 'accompaniment', 'accompaniments', 'accompanist', 'accompanists', 'accompany', 'accompanying', 'accomplice', 'accomplices', 'accord', 'accordance', 'accordant', 
        'accorded', 'accorder', 'according', 'accordingly', 'accordings', 'accords', 'accost', 'accosted', 'accosting', 'accosts', 'account', 'accountable', 'accountancy', 'accountant', 'accountants', 
        'accounted', 'accounted for', 'accounting', 'accountings', 'accounts', 'accounts receivable', 'accrual', 'accruals', 'accrue', 'accrued', 'accrued income', 'accrued interest', 'accrues', 'accruing', 'acculturation', 
        'acculturative', 'acculturize', 'acculturized', 'acculturizes', 'acculturizing', 'accumulate', 'accumulated', 'accumulates', 'accumulating', 'accumulation', 'accumulations', 'accumulative', 'accumulatively', 'accumulativeness', 'accumulator', 
        'accumulators', 'accuracy', 'accurate', 'accurately', 'accurateness', 'accursed', 'accursedly', 'accursedness', 'accurst', 'accurstion', 'accusable', 'accusal', 'accusation', 'accusations', 'accusative', 
        'accusatively', 'accusativeness', 'accusatives', 'accusator', 'accusatorial', 'accusatorially', 'accusatorious', 'accusatoriously', 'accusators', 'accusatory', 'accuse', 'accused', 'accuser', 'accusers', 'accuses', 
        'accusing', 'accusingly', 'accusingness', 'acerbates', 'acerbating', 'acerbation', 'acerbic', 'acerbical', 'acerbically', 'acerbicate', 'acerbicated', 'acerbicates', 'acerbicating', 'acerbication', 'acerbities', 
        'acerbity', 'acerbly', 'acerbness', 'acervate', 'acervated', 'acervation', 'acquaintance', 'acquaintances', 'acquaintanceship', 'acquainted', 'acquaintedness', 'acquainting', 'addict', 'admirer', 'adversary', 
        'aficionado', 'age group', 'ally', 'ancestry', 'antagonist', 'associate', 'aunt', 'auntie', 'aunty', 'baby', 'beloved', 'best friend', 'bff', 'big brother', 'big sister', 
        'bloodline', 'boy', 'bride', 'bro', 'brother', 'brother-in-law', 'brotherhood', 'buddy', 'buff', 'child', 'children', 'circle', 'civilization', 'clan', 'clique', 
        'close friend', 'closed circle', 'cohort', 'colleague', 'collective', 'community', 'companion', 'competitor', 'comrade', 'concubine', 'confidant', 'confidante', 'conjugal', 'connection', 'contact', 
        'couple', 'cousin', 'coworker', 'crew', 'crush', 'culture', 'dad', 'daddy', 'darling', 'daughter', 'daughter-in-law', 'dear', 'dearest', 'demographic', 'descent', 
        'devotee', 'duo', 'enemy', 'enthusiast', 'equal', 'establishment', 'extended family', 'family', 'fan', 'fanatic', 'father', 'father-in-law', 'filial', 'first cousin', 'flame', 
        'foe', 'folks', 'fraternal', 'frenemy', 'friend', 'friendship', 'gang', 'geek', 'generation', 'girl', 'gramps', 'grandchild', 'granddad', 'granddaughter', 'grandfather', 
        'grandma', 'grandmother', 'grandpa', 'grandparent', 'grandpop', 'grandson', 'great grandchild', 'great grandparent', 'great-grandchild', 'great-grandparent', 'groom', 'group', 'guest', 'heritage', 'hero', 
        'heroine', 'honey', 'host', 'hostess', 'household', 'husband', 'identical', 'idol', 'in-crowd', 'in-law', 'infant', 'inner circle', 'inspiration', 'institution', 'interloper', 
        'intimate', 'intimate circle', 'intruder', 'junkie', 'juvenile', 'kid', 'kids', 'kin', 'kindred spirit', 'kinship', 'kissing cousin', 'lad', 'lass', 'lineage', 'little brother', 
        'little one', 'little sister', 'love', 'lover', 'mama', 'marital', 'marriage', 'masses', 'mate', 'matrimonial', 'matrimony', 'mentor', 'minor', 'mistress', 'mite', 
        'mom', 'mommy', 'mother', 'mother-in-law', 'mum', 'mummy', 'nemesis', 'nerd', 'network', 'newlywed', 'nuclear family', 'old flame', 'old lady', 'old man', 'open community', 
        'opponent', 'organization', 'out-crowd', 'outer circle', 'outsider', 'pair', 'pal', 'papa', 'pappy', 'paramour', 'parent', 'parental', 'partner', 'partner-in-crime', 'peer', 
        'peer group', 'people', 'populace', 'population', 'posse', 'protagonist', 'protégé', 'public', 'relation', 'relative', 'rival', 'role model', 'second cousin', 'sibling', 'sis', 
        'sister', 'sister-in-law', 'sisterhood', 'social circle', 'society', 'son', 'son-in-law', 'soulmate', 'spouse', 'squad', 'step-child', 'step-parent', 'step-sibling', 'stepbrother', 'stepdaughter', 
        'stepfather', 'stepmother', 'stepsister', 'stepson', 'stranger', 'sweetheart', 'teammate', 'third cousin', 'toddler', 'tribe', 'twin', 'twosome', 'tyke', 'unc', 'uncle', 
        'union', 'villain', 'visitor', 'wedlock', 'wife', 'young one', 'youngster', 'youth'
    ],
    // activities: 675 words
    activities: [
        'abandon', 'abseiling', 'absorb', 'abstaining', 'accelerate', 'accelerating', 'accept', 'accepting', 'accessing', 'accommodate', 'accommodating', 'accompany', 'accomplishing', 'according', 'accruing', 
        'achieving', 'acknowledge', 'acknowledging', 'acquiring', 'acquitting', 'acting', 'activating', 'adapting', 'adding', 'addressing', 'adhering', 'adjourn', 'adjust', 'adjusting', 'administering', 
        'admiring', 'admit', 'admit defeat', 'admitting', 'adopt', 'adopting', 'adoring', 'adorning', 'advance', 'advancing', 'advertise', 'advertising', 'advising', 'advocating', 'affecting', 
        'affording', 'agreeing', 'aid', 'aiding', 'ailing', 'aiming', 'airing', 'alarming', 'alienating', 'aligning', 'alleging', 'alleviating', 'allocate', 'allotting', 'allow', 
        'allowing', 'alluding', 'alluring', 'allying', 'alter', 'altering', 'alternating', 'amalgamating', 'amassing', 'amazing', 'amending', 'amplifying', 'amuse', 'amusing', 'analyze', 
        'analyzing', 'anchoring', 'animating', 'announce', 'announcing', 'annoying', 'annulling', 'answering', 'antagonizing', 'anticipating', 'appealing', 'appearing', 'appease', 'appeasing', 'appending', 
        'applauding', 'applying', 'appointing', 'appraise', 'appreciating', 'apprehending', 'approaching', 'approve', 'approving', 'approximating', 'arbitrate', 'arbitrating', 'argue', 'arrange', 'arranging', 
        'arresting', 'arrive', 'arriving', 'articulate', 'articulating', 'ascending', 'ascertaining', 'ascribing', 'asking', 'aspiring', 'assailing', 'assaulting', 'assemble', 'assembling', 'assenting', 
        'asserting', 'assess', 'assessing', 'assign', 'assigning', 'assimilating', 'assist', 'assisting', 'associating', 'assorting', 'assuaging', 'assuming', 'assuring', 'astonishing', 'astounding', 
        'attaching', 'attacking', 'attaining', 'attempting', 'attend', 'attend to', 'attending', 'attest', 'attesting', 'attracting', 'attuning', 'auctioning', 'audit', 'auditing', 'augmenting', 
        'authenticate', 'authenticating', 'authorize', 'authorizing', 'avenging', 'averting', 'avoid', 'avoiding', 'awaiting', 'awakening', 'awarding', 'bake', 'bargain', 'battle', 'begin', 
        'bend', 'bid farewell', 'blend', 'block', 'board', 'boil', 'brake', 'break', 'breed', 'broadcast', 'build', 'bump', 'burn', 'calm', 'capitulate', 
        'capture', 'care', 'carry', 'catch', 'categorize', 'cater to', 'cease', 'celebrate', 'change', 'chase', 'chat', 'check', 'chew', 'chill', 'chill out', 
        'chop', 'circulate', 'classify', 'clean', 'climb', 'close', 'collect', 'collide', 'colonize', 'combat', 'combine', 'come back', 'commemorate', 'commence', 'commend', 
        'communicate', 'complain', 'compliment', 'comprehend', 'compress', 'conceal', 'concede', 'conclude', 'condense', 'confess', 'confirm', 'congratulate', 'congregate', 'construct', 'contemplate', 
        'control', 'convene', 'converse', 'convert', 'convey', 'convince', 'cook', 'cool', 'cool off', 'crash', 'create', 'criticize', 'critique', 'crouch', 'crush', 
        'cry', 'cultivate', 'cure', 'curve', 'cut', 'dance', 'debate', 'debut', 'decelerate', 'declare', 'decompress', 'decree', 'defend', 'defer', 'deflate', 
        'delay', 'delegate', 'deliver', 'demonstrate', 'demote', 'depart', 'describe', 'design', 'diagnose', 'dial back', 'dice', 'diffuse', 'direct', 'disband', 'discard', 
        'disclose', 'discontinue', 'discover', 'discuss', 'disembark', 'disperse', 'display', 'dispose', 'distribute', 'divide', 'divulge', 'dock', 'document', 'dodge', 'drag', 
        'draw', 'drink', 'drip', 'drive', 'drop', 'duck', 'dust', 'dwell', 'ease up', 'eat', 'elevate', 'embark', 'embrace', 'emigrate', 'emit', 
        'empower', 'enable', 'encounter', 'encourage', 'end', 'endorse', 'engage', 'enhance', 'entertain', 'escape', 'escort', 'establish', 'evade', 'evaluate', 'evaporate', 
        'exaggerate', 'examine', 'exhibit', 'expand', 'experience', 'explain', 'explore', 'expose', 'express', 'extinguish', 'facilitate', 'feel', 'fight', 'file', 'find', 
        'finish', 'fix', 'flee', 'flex', 'flood', 'flow', 'fluctuate', 'fly', 'follow', 'fortify', 'found', 'freeze', 'frown', 'gather', 'give in', 
        'give up', 'glow', 'go away', 'grab', 'grasp', 'greet', 'grind', 'gripe', 'grow', 'grumble', 'guard', 'guide', 'haggle', 'halt', 'harvest', 
        'hasten', 'heal', 'heat', 'help', 'hide', 'hinder', 'hit', 'hold', 'honor', 'humor', 'hunt', 'hurry', 'hype', 'ignite', 'immigrate', 
        'impede', 'improve', 'inflate', 'inform', 'inhabit', 'initiate', 'inspect', 'inspire', 'interpret', 'introduce', 'investigate', 'joke', 'journey', 'judge', 'jump', 
        'keep', 'kick', 'land', 'laugh', 'launch', 'lead', 'leak', 'learn', 'leave', 'leave behind', 'let up', 'lie', 'light', 'linger', 'list', 
        'lock', 'lodge', 'look', 'maintain', 'make', 'make peace', 'manage', 'march', 'market', 'maximize', 'mediate', 'meditate', 'meet', 'mellow out', 'melt', 
        'memorialize', 'migrate', 'minimize', 'mix', 'modify', 'monitor', 'mop', 'motivate', 'move', 'mumble', 'murmur', 'mutiny', 'mutter', 'narrate', 'negotiate', 
        'notice', 'notify', 'nurse', 'object', 'oblige', 'observe', 'obstruct', 'occupy', 'open', 'open up', 'oppose', 'organize', 'oscillate', 'overstate', 'paint', 
        'pause', 'perceive', 'perform', 'permit', 'persuade', 'pick', 'picket', 'placate', 'plan', 'plant', 'play', 'pluck', 'polish', 'ponder', 'postpone', 
        'pour', 'praise', 'premiere', 'prepare', 'present', 'preserve', 'prevent', 'print', 'proclaim', 'promote', 'prompt', 'protect', 'protest', 'publicize', 'publish', 
        'pull', 'punch', 'punish', 'pursue', 'push', 'put out', 'quit', 'radiate', 'rain', 'raise', 'rally', 'ratify', 'read', 'realize', 'reason', 
        'rebel', 'recall', 'receive', 'record', 'reflect', 'refract', 'reinforce', 'relax', 'relocate', 'remain', 'remember', 'remind', 'reminisce', 'repair', 'report', 
        'reschedule', 'reside', 'resign', 'resist', 'rest', 'retain', 'retire', 'retreat', 'return', 'reveal', 'review', 'revolt', 'reward', 'ride', 'rip', 
        'rotate', 'rule', 'run', 'run away', 'rush', 'safeguard', 'sail', 'sanction', 'scatter', 'scream', 'scrub', 'scrutinize', 'sculpt', 'seal', 'search', 
        'secure', 'see', 'seek', 'seize', 'send', 'sense', 'sentence', 'separate', 'serve', 'set up', 'settle', 'settle down', 'share', 'shelter', 'shield', 
        'shift', 'shine', 'shout', 'show', 'shower', 'shred', 'shrink', 'shrivel', 'shut', 'sign', 'simmer', 'simmer down', 'sing', 'sit', 'sketch', 
        'sleep', 'slice', 'slow down', 'smile', 'sob', 'soothe', 'sort', 'spark', 'speak', 'speed up', 'spill', 'spin', 'splash', 'split', 'spray', 
        'sprinkle', 'stand', 'start', 'state', 'stay', 'stir', 'stop', 'store', 'straighten', 'strengthen', 'stretch', 'strike', 'study', 'support', 'surrender', 
        'sustain', 'swallow', 'sweep', 'swell', 'swim', 'swirl', 'take off', 'talk', 'tame', 'taste', 'teach', 'tear', 'tell', 'terminate', 'test', 
        'think', 'throw', 'throw in the towel', 'tidy', 'tone down', 'toss', 'tout', 'train', 'transform', 'transition', 'translate', 'transport', 'trap', 'travel', 'treat', 
        'tribute', 'turn', 'twirl', 'twist', 'uncover', 'understand', 'understate', 'unfold', 'unfurl', 'unload', 'unlock', 'unpack', 'unroll', 'unseal', 'unveil', 
        'unwind', 'unwrap', 'uphold', 'urge', 'vacuum', 'validate', 'vary', 'verify', 'vibrate', 'view', 'voyage', 'wage war', 'wait', 'wake', 'walk', 
        'warm', 'warm up', 'wash', 'watch', 'weep', 'welcome', 'whine', 'whirl', 'whisper', 'wipe', 'withdraw', 'witness', 'work', 'write', 'yell'
    ],
    // hobbiesActivities: 370 words
    hobbiesActivities: [
        'academic pursuits', 'acrobatics', 'activism', 'advocacy', 'aerobics', 'afrobeat', 'air hockey', 'airbrush', 'airplane spotting', 'airsoft', 'alternative', 'amateur radio', 'ambient', 'americana collecting', 'animal care', 
        'animation', 'anime', 'antique collecting', 'antique dealing', 'antiques', 'antiquing', 'app development', 'appraising', 'aquascaping', 'archaeology', 'archery', 'architecture', 'art', 'art collecting', 'art deco', 
        'art glass', 'art history', 'art nouveau', 'art therapy', 'artificial intelligence', 'artisan crafting', 'artistic pursuits', 'artistry', 'arts and crafts', 'artwork', 'astronomy', 'astrophotography', 'athletics', 'attending events', 'audiobooks', 
        'augmented reality', 'aviation', 'aviator', 'backpacking', 'badminton', 'bagpipe', 'baking', 'balancing', 'ballet', 'ballooning', 'band', 'banjo', 'banking', 'base jumping', 'baseball', 
        'basketball', 'bass', 'bassoon', 'batik', 'baton', 'batting', 'battle re-enactment', 'bead wrapping', 'beading', 'beadwork', 'beaming', 'bearing', 'beat', 'beatboxing', 'beating', 
        'beauty', 'beauty pageant', 'beekeeping', 'beelining', 'bellydancing', 'belt sander', 'belting', 'benchmarking', 'benchwarm', 'bending', 'beneficial gardening', 'benefiting', 'bengal', 'benign activity', 'bent activity', 
        'bergamot', 'berlin', 'bermuda', 'berth', 'beryllium', 'beseech', 'beset', 'besetting', 'besieging', 'besirching', 'besmearing', 'besmirching', 'besmutching', 'besotting', 'bespangling', 
        'bespatter', 'bespattered', 'bespattering', 'bespotting', 'bespoutting', 'besprent', 'besprinkling', 'besprout', 'bespuming', 'bestainning', 'bestarching', 'bestarring', 'bestead', 'besteading', 'besteal', 
        'biology', 'blogging', 'blues', 'board games', 'boxing', 'breakdancing', 'bungee jumping', 'business', 'camping', 'canoeing', 'car racing', 'card games', 'cardio', 'cello', 'charity', 
        'chemistry', 'chess', 'cinema', 'clarinet', 'classical', 'classical music', 'climbing', 'clubbing', 'coding', 'coin collecting', 'collecting', 'comedy', 'comedy shows', 'comics', 'community service', 
        'composition', 'concerts', 'contemporary', 'content creation', 'cooking', 'cosplay', 'country', 'crafting', 'creative writing', 'crypto', 'cybersecurity', 'cycling', 'dancing', 'dancing styles', 'data science', 
        'decorating', 'discord', 'diy', 'dj-ing', 'dnd', 'drama', 'drawing', 'drum-and-bass', 'drums', 'dubstep', 'dungeons and dragons', 'edm', 'electronic', 'embroidery', 'emo', 
        'entrepreneurship', 'essay writing', 'experimental', 'facebook', 'fan communities', 'fashion', 'festivals', 'fiction', 'filmmaking', 'fishing', 'fitness', 'flute', 'folk', 'football', 'forums', 
        'free running', 'game development', 'gaming', 'gardening', 'geology', 'golf', 'graphic novels', 'grooming', 'growing', 'guitar', 'gym', 'hacking', 'hardcore', 'harmonica', 'harp', 
        'hiking', 'hip-hop', 'history', 'home improvement', 'house', 'hunting', 'ice climbing', 'improv', 'indie', 'instagram', 'instrument playing', 'interior design', 'investing', 'jazz', 'jewelry making', 
        'jogging', 'journalism', 'judo', 'karate', 'kayaking', 'keyboard', 'kickboxing', 'knitting', 'krumping', 'landscaping', 'language learning', 'larping', 'latin', 'lindyhop', 'linkedin', 
        'locking', 'lyric writing', 'machine learning', 'makeup', 'mandolin', 'manga', 'martial arts', 'meditation', 'memorabilia', 'metal', 'metalworking', 'miniature painting', 'model building', 'motocross', 'motorcycling', 
        'motorsports', 'mountaineering', 'movies', 'music genres', 'music production', 'musicals', 'nfts', 'oboe', 'online communities', 'opera', 'organ', 'painting', 'parkour', 'partying', 'pet care', 
        'philosophy', 'photography', 'physics', 'piano', 'pilates', 'pinterest', 'planting', 'playing music', 'podcasts', 'poetry', 'poker', 'pop', 'pop-punk', 'popping', 'pottery', 
        'programming', 'punk', 'racing', 'rap', 'reading', 'real estate', 'reddit', 'reenactment', 'reggae', 'research', 'rock', 'rock climbing', 'rowing', 'running', 'salsa', 
        'saxophone', 'science', 'screamo', 'sculpting', 'self defense', 'sewing', 'shows', 'sightseeing', 'singing', 'ska', 'skateboarding', 'skating', 'sketching', 'skiing', 'skincare', 
        'skydiving', 'snowboarding', 'soccer', 'social media', 'socializing', 'songwriting', 'sports', 'stamp collecting', 'stand-up', 'stocks', 'streaming', 'strength training', 'studying', 'styling', 'subreddits', 
        'surfing', 'swimming', 'swing', 'synthesizer', 'tabletop rpg', 'taekwondo', 'tango', 'tap', 'techno', 'technology', 'tennis', 'theater', 'tiktok', 'trance', 'travel', 
        'trombone', 'trumpet', 'turntables', 'twitter', 'ukulele', 'video games', 'videography', 'violin', 'virtual reality', 'vlogging', 'vogue', 'voguing', 'volunteering', 'walking', 'waltz', 
        'warhammer', 'web development', 'weightlifting', 'woodworking', 'world music', 'wrestling', 'writing', 'yoga', 'youtube', 'zip-lining'
    ],
    // foodDrinks: 263 words
    foodDrinks: [
        'abalone', 'absinthe', 'acai', 'acai bowl', 'acai juice', 'acanthus', 'acanthus berries', 'acanthus leaves', 'acanthus vegetables', 'acerola', 'acerola juice', 'acetal', 'acetate', 'acetic acid', 'acetifier', 
        'acetify', 'acetize', 'acetone', 'acetum', 'achene', 'achery', 'aches', 'acheta', 'achillea', 'achingly', 'acid drop', 'acid fruits', 'affogato', 'alcohol', 'almond', 
        'americano', 'apple', 'avocado oil', 'bagel', 'bake', 'bakery', 'banana', 'bean', 'beef', 'beer', 'berries', 'beverage', 'bistro', 'black tea', 'blackberry', 
        'blend', 'blueberry', 'boil', 'bread', 'breakfast', 'broccoli', 'broil', 'brownie', 'brunch', 'buffet', 'burger joint', 'butter', 'cafe', 'cake', 'canola oil', 
        'cappuccino', 'carrot', 'cashew', 'cauliflower', 'celery', 'cereal', 'chamomile', 'cheese', 'chia', 'chicken', 'chickpea', 'chop', 'clam', 'cocoa', 'coconut oil', 
        'cod', 'coffee', 'cold brew', 'condiment', 'cook', 'cookie', 'cortado', 'crab', 'cranberry', 'cream', 'croissant', 'crush', 'cucumber', 'cupcake', 'dairy', 
        'delivery', 'dice', 'dine in', 'diner', 'dinner', 'donut', 'dressing', 'drink', 'eating out', 'egg', 'energy drink', 'espresso', 'fast food', 'feast', 'fish', 
        'flat white', 'flatten', 'flavor', 'flax', 'food truck', 'from scratch', 'fruit', 'fry', 'garlic', 'ginger', 'granola', 'grape', 'grate', 'gravy', 'green tea', 
        'grill', 'guacamole', 'hazelnut', 'herb', 'herbal tea', 'home cooked', 'homemade', 'hot chocolate', 'hot sauce', 'hummus', 'iced coffee', 'iced lemonade', 'iced tea', 'ingredients', 'juice', 
        'kale', 'ketchup', 'knead', 'kombucha', 'lamb', 'latte', 'lemon', 'lemonade', 'lentil', 'lettuce', 'lime', 'lobster', 'lunch', 'lungo', 'macadamia', 
        'macchiato', 'mango', 'margarine', 'mayo', 'meal', 'meat', 'melon', 'milk', 'milkshake', 'mince', 'mocha', 'mold', 'muffin', 'mussel', 'mustard', 
        'noodle', 'nuts', 'oatmeal', 'oil', 'olive oil', 'onion', 'orange', 'oyster', 'pasta', 'pastry', 'peach', 'peanut', 'peanut oil', 'pecan', 'pepper', 
        'peppermint', 'pesto', 'pie', 'pineapple', 'pistachio', 'pizzeria', 'plate', 'plum', 'pork', 'potato', 'potluck', 'protein shake', 'pumpkin', 'puree', 'raspberry', 
        'recipe', 'relish', 'restaurant', 'rice', 'ristretto', 'roast', 'roll', 'salmon', 'salsa', 'salt', 'sandwich shop', 'sauce', 'sauté', 'scallop', 'scramble', 
        'seasoning', 'seeds', 'seitan', 'serve', 'sesame', 'sesame oil', 'shape', 'shellfish', 'shred', 'shrimp', 'sift', 'simmer', 'slice', 'slow food', 'smoothie', 
        'snack', 'soda', 'sour cream', 'soy sauce', 'spice', 'spinach', 'spread', 'steam', 'stir', 'strain', 'strawberry', 'street food', 'sunflower', 'supper', 'sweet potato', 
        'taco stand', 'takeout', 'tart', 'taste', 'tea', 'tempeh', 'teriyaki', 'toast', 'tofu', 'tomato', 'tuna', 'turkey', 'vegetable', 'vegetable oil', 'vinaigrette', 
        'vinegar', 'walnut', 'water', 'watermelon', 'whipped cream', 'whisk', 'wine', 'yogurt'
    ],
    // utilities: 221 words
    utilities: [
        'ablate', 'ablated', 'ablating', 'ablation', 'ablative', 'ablator', 'ablaze', 'able', 'able-bodied', 'ablely', 'ableness', 'abloom', 'ablubbed', 'ablue', 'abluer', 
        'abluerest', 'ablues', 'abluing', 'ablush', 'abluted', 'ablutes', 'abluting', 'ablution', 'ablutionary', 'ablutions', 'ablutophobia', 'abluyingly', 'ably', 'abmho', 'abmhos', 
        'abnegation', 'abnegations', 'abnegative', 'abnegator', 'abnegators', 'abnormal', 'abnormalism', 'abnormalisms', 'abnormalist', 'abnormalists', 'abnormalities', 'abnormality', 'abnormalize', 'abnormalized', 'abnormalizes', 
        'abnormalizing', 'abnormally', 'abnormity', 'about', 'accumulation', 'across', 'afternoon', 'agenda', 'aggregation', 'ahead of schedule', 'alarm', 'alert', 'always', 'annual', 'appointment', 
        'approximately', 'around', 'assemblage', 'assembly', 'asterisk', 'behind schedule', 'biannual', 'birthday', 'bunch', 'calendar', 'call', 'check', 'check list', 'check mark', 'check-list', 
        'checkbox', 'checklist', 'checkmark', 'clock', 'collection', 'compilation', 'congregation', 'consistently', 'constantly', 'continually', 'continuously', 'cross', 'cross mark', 'current', 'daily', 
        'dash', 'dawn', 'daybreak', 'deadline', 'due', 'due date', 'duration', 'dusk', 'earliest', 'early', 'email', 'eternally', 'evening', 'event', 'evermore', 
        'expiration', 'expired', 'expires', 'for all time', 'forever', 'forever and ever', 'frequency', 'frequently', 'gathering', 'hash', 'hash tag', 'hashtag', 'heap', 'hourly', 'hyphen', 
        'in the nick of time', 'inconsistently', 'intermittently', 'interval', 'invalid', 'inventory', 'itinerary', 'just in time', 'late', 'later', 'latest', 'length', 'list', 'listing', 'little', 
        'lots', 'mark', 'meeting', 'message', 'microsecond', 'midnight', 'millisecond', 'minute', 'monthly', 'morning', 'nanosecond', 'never', 'new', 'night', 'noon', 
        'note', 'notes', 'notification', 'number sign', 'occasionally', 'old', 'on schedule', 'on time', 'outdated', 'over', 'perpetually', 'phone call', 'pile', 'plan', 'planner', 
        'planning', 'pound', 'pound sign', 'punctual', 'punctually', 'quarterly', 'recent', 'recurrence', 'recurring', 'regularly', 'reminder', 'repeat', 'right on time', 'roster', 'roughly', 
        'schedule', 'scheduled', 'second', 'semi-annual', 'sms', 'some', 'sometimes', 'soon', 'sooner', 'span', 'sporadically', 'stack', 'star', 'sundown', 'sunrise', 
        'sunset', 'sunup', 'tardy', 'task', 'text', 'throughout', 'tick', 'time', 'time frame', 'time period', 'time slot', 'time table', 'timer', 'timetable', 'to do', 
        'to-do', 'todo', 'twilight', 'underscore', 'updated', 'valid', 'voicemail', 'weekly', 'whatsapp', 'x mark', 'yearly'
    ],
    // places: 188 words
    places: [
        'abbey', 'abbeys', 'abbot', 'abbots', 'abbotship', 'abbrev', 'abbreviated', 'abbreviating', 'abbreviation', 'abbreviations', 'abbreviator', 'abbreviators', 'abbrevs', 'abbrieviate', 'abdomen', 
        'abdomens', 'abdominal', 'abdominally', 'abdominals', 'abdomino-cervical', 'abdomino-pelvic', 'abdomino-scrotal', 'abdomino-thoracic', 'abdominoscopy', 'abdominothoracic', 'abdominous', 'abducens', 'abducent', 'abducentes', 'abduces', 
        'abducing', 'abduction', 'abductions', 'abductive', 'abductively', 'abductor', 'abductores', 'abductors', 'abelian', 'abelian group', 'abelian groups', 'airport', 'alley', 'anchorage', 'apartment', 
        'arena', 'asylum', 'avenue', 'bank', 'bar', 'base', 'battlefield', 'beach', 'boulevard', 'bridge', 'building', 'bunker', 'burrow', 'bus station', 'cabin', 
        'cafe', 'camp', 'car wash', 'castle', 'cemetery', 'church', 'cinema', 'city', 'clinic', 'college', 'colony', 'condo', 'continent', 'corner', 'cottage', 
        'country', 'countryside', 'court', 'den', 'dentist', 'district', 'dock', 'doctor', 'downtown', 'empire', 'field', 'fire station', 'forest', 'fort', 'fortress', 
        'freeway', 'garden', 'gas station', 'graveyard', 'grocery', 'gym', 'harbor', 'haven', 'hideaway', 'highway', 'hive', 'home', 'hospital', 'hotel', 'house', 
        'intersection', 'island', 'kingdom', 'lair', 'lake', 'lane', 'library', 'mall', 'mansion', 'marina', 'market', 'metropolitan area', 'mosque', 'motel', 'mountain', 
        'museum', 'nation', 'neighborhood', 'nest', 'ocean', 'office', 'palace', 'park', 'parking lot', 'path', 'perch', 'pharmacy', 'pier', 'planet', 'playground', 
        'police station', 'port', 'post office', 'province', 'pub', 'quarter', 'refuge', 'region', 'republic', 'resort', 'restaurant', 'retreat', 'river', 'road', 'roost', 
        'rural area', 'safe house', 'sanctuary', 'school', 'secret hideout', 'settlement', 'shelter', 'shop', 'sidewalk', 'skyscraper', 'space', 'stadium', 'state', 'stop sign', 'store', 
        'street', 'suburbs', 'subway', 'supermarket', 'synagogue', 'temple', 'territory', 'theater', 'tower', 'town', 'traffic light', 'trail', 'train station', 'trench', 'tunnel', 
        'university', 'uptown', 'urban area', 'valley', 'village', 'warren', 'world', 'zone'
    ],
    // timeWords: 121 words
    timeWords: [
        'a.m.', 'aback', 'abaft', 'abandoned', 'abase', 'abased', 'abasement', 'abaser', 'abasing', 'adventure', 'afternoon', 'age', 'april', 'august', 'autumn', 
        'awakening', 'blaze', 'break', 'brightness', 'century', 'conflagration', 'cycle', 'darkness', 'dawn', 'day', 'decade', 'december', 'doze', 'dream', 'dusk', 
        'epoch', 'era', 'evening', 'excursion', 'expedition', 'fall', 'february', 'flame', 'flash', 'flicker', 'frequency', 'friday', 'getting up', 'gleam', 'glimmer', 
        'glow', 'hiatus', 'holiday', 'hour', 'illumination', 'inferno', 'instant', 'intermission', 'january', 'journey', 'july', 'june', 'light', 'march', 'may', 
        'midnight', 'millennium', 'minute', 'moment', 'monday', 'month', 'morning', 'nap', 'night', 'noon', 'november', 'now', 'october', 'orbit', 'outing', 
        'pace', 'pause', 'period', 'quest', 'rate', 'recess', 'respite', 'rest', 'revolution', 'rising', 'rotation', 'sabbatical', 'saturday', 'second', 'september', 
        'shine', 'siesta', 'sleep', 'slumber', 'sparkle', 'speed', 'spring', 'summer', 'sunday', 'sunrise', 'sunset', 'tempo', 'thursday', 'today', 'tomorrow', 
        'tonight', 'tour', 'trip', 'tuesday', 'twilight', 'twinkle', 'vacation', 'voyage', 'waking', 'wednesday', 'week', 'weekday', 'weekend', 'winter', 'year', 
        'yesterday'
    ],
    // commonQuestions: 46 words
    commonQuestions: [
        'are they coming', 'are they done', 'are they going', 'are they here', 'are they ready', 'are they serious', 'are they there', 'are things ok', 'are we done', 'are we done yet', 'are we going', 'are we ready', 'are we there', 'are we there yet', 'are you alright', 
        'are you being serious', 'are you busy', 'are you done', 'are you finished', 'are you for real', 'are you free', 'are you going', 'are you joking', 'are you kidding', 'are you ok', 'are you ready', 'are you serious', 'are you sure', 'are you there', 'are you tired', 
        'aren't you', 'aren't you angry', 'aren't you bored', 'aren't you busy', 'aren't you concerned', 'aren't you curious', 'aren't you done', 'aren't you excited', 'aren't you finished', 'aren't you free', 'aren't you going', 'aren't you interested', 'aren't you ready', 'aren't you sure', 'aren't you tired', 
        'aren't you worried'
    ],
    // pronouns: 68 words
    pronouns: [
        'a', 'all', 'anybody', 'anyone', 'anything', 'anywhere', 'both', 'each', 'either', 'everybody', 'everyone', 'everything', 'everywhere', 'few', 'her', 
        'hers', 'herself', 'him', 'himself', 'his', 'i', 'its', 'itself', 'many', 'mine', 'myself', 'neither', 'no one', 'nobody', 'none', 
        'nothing', 'nowhere', 'our', 'ours', 'ourself', 'ourselves', 'several', 'she', 'some', 'somebody', 'someone', 'something', 'somewhere', 'that', 'the', 
        'their', 'theirs', 'them', 'themself', 'themselves', 'these', 'they', 'this', 'those', 'what', 'whatever', 'which', 'whichever', 'who', 'whoever', 
        'whom', 'whomever', 'whose', 'you', 'your', 'yours', 'yourself', 'yourselves'
    ],
    // questions: 82 words
    questions: [
        'always', 'are', 'ask', 'asked', 'been', 'can', 'can you', 'could', 'could you', 'did', 'did you', 'do you', 'does', 'does he', 'ever', 
        'get', 'got', 'had', 'hardly', 'has', 'have', 'how', 'how about', 'how are', 'how come', 'how is', 'how long', 'how many', 'how much', 'how's it going', 
        'is it', 'is there', 'knew', 'know', 'made', 'make', 'may', 'mean', 'meant', 'might', 'must', 'never', 'often', 'rarely', 'scarcely', 
        'seldom', 'shall', 'should', 'sometimes', 'tell', 'think', 'thought', 'told', 'understand', 'understood', 'usually', 'was', 'were', 'what', 'what about', 
        'what are', 'what do', 'what does', 'what if', 'what is', 'what's', 'when', 'when are', 'when did', 'when will', 'where', 'where are', 'where is', 'which', 'who', 
        'whom', 'whose', 'why', 'will', 'would', 'would you', 'wouldn't'
    ],
};

/*
Vocabulary Statistics:
  verbs               : 1575 words
  emotions            :  481 words
  adjectives          :  537 words
  nouns               :  664 words
  commonPhrases       :  157 words
  responses           :  495 words
  work                :  358 words
  relationships       :  353 words
  activities          :  675 words
  hobbiesActivities   :  370 words
  foodDrinks          :  263 words
  utilities           :  221 words
  places              :  188 words
  timeWords           :  121 words
  commonQuestions     :   46 words
  pronouns            :   68 words
  questions           :   82 words
  TOTAL               : 6654 words
*/

if (typeof module !== 'undefined' && module.exports) {
    module.exports = vocabulary;
}
